# This workflow is managed by gh actions-lock.
# SPDX-License-Identifier: MPL-2.0
name: Scorecards supply-chain security

on:
  branch_protection_rule:
  schedule:
    - cron: '23 4 * * 1'

permissions: read-all

jobs:
  analysis:
    uses: hyperpolymath/standards/.github/workflows/scorecard-reusable.yml@d200ddcafb7f7336b0ae0353ea1504153876d6f2
    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write
